package com.ajrpachon.chatapp.data.local

import android.app.Application
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import java.io.File
import org.json.JSONObject
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Keeps the exported schema honest. `app/schemas/.../<version>.json` is generated by KSP from the
 * entities; if someone changes an entity and forgets to bump the version and export the new file,
 * the exported JSON and the real database disagree and this fails. It is also the safety net that
 * will matter the day the first migration is written.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35], application = Application::class)
class ChatDatabaseSchemaTest {

    private lateinit var db: ChatDatabase

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            ChatDatabase::class.java,
        ).allowMainThreadQueries().build()
    }

    @After
    fun tearDown() = db.close()

    private fun exportedSchema(version: Int): JSONObject {
        val dir = listOf(File("schemas"), File("app/schemas")).first { it.exists() }
        val file = dir.walkTopDown().first { it.name == "$version.json" }
        return JSONObject(file.readText()).getJSONObject("database")
    }

    private fun queryStrings(sql: String): List<String> =
        db.openHelper.writableDatabase.query(sql).use { cursor ->
            buildList { while (cursor.moveToNext()) add(cursor.getString(0)) }
        }

    @Test
    fun `the database is created at the exported version`() {
        val exportedVersion = exportedSchema(db.openHelper.readableDatabase.version).getInt("version")

        assertEquals(1, exportedVersion)
        assertEquals(exportedVersion, db.openHelper.readableDatabase.version)
    }

    @Test
    fun `the tables of the real database are exactly the exported entities`() {
        val entities = exportedSchema(1).getJSONArray("entities")
        val exportedTables = (0 until entities.length()).map { entities.getJSONObject(it).getString("tableName") }.toSet()

        val realTables = queryStrings(
            "SELECT name FROM sqlite_master WHERE type = 'table' " +
                "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'android_%' AND name != 'room_master_table'",
        ).toSet()

        assertEquals(exportedTables, realTables)
    }
}
